default_platform(:ios)

platform :ios do
  desc "Build iOS y subir a TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: Base64.decode64(ENV["ASC_KEY_B64"]),
      in_house: false
    )

    create_keychain(
      name: "build.keychain",
      password: "ci",
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    match(
      type: "appstore",
      app_identifier: ENV["APP_IDENTIFIER"],
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      readonly: false,
      keychain_name: "build.keychain",
      keychain_password: "ci",
      api_key: api_key
    )

    sh "npm ci || npm install"
    # Asegura que la plataforma iOS exista en el runner
    sh "npx cap add ios || true"
    sh "npx ionic build --prod"
    sh "npx cap sync ios"

    increment_build_number(
      xcodeproj: "ios/App/App.xcodeproj",
      build_number: Time.now.strftime('%Y%m%d%H%M')
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "build",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
