name: iOS Beta (TestFlight)

on:
  workflow_dispatch: {}   # lo lanzas manualmente

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar bundler y gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install

      - name: Build web y Capacitor
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm ci || npm install
          npx ionic --version || npx -y @ionic/cli --version
          npx cap add ios || true
          npx ionic build --prod
          npx cap sync ios

      - name: Fastlane beta (TestFlight)
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_B64: ${{ secrets.ASC_KEY_B64 }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: bundle exec fastlane beta
